#! /bin/bash

function error_free(){
        if(($?==0));
        then
                echo -e "Successful execution for creating \c"
        else
                echo "Unscessful execution with an error $1"
        fi
}

function listing_data(){
        ls -al *.txt
        ps aux > ./process_info.txt
        error_free
        echo "process information list"
        free -h > ./memory_info.txt
        error_free
        echo "memory usage list"
        df -h | awk '{print $1,$5,$6}' > ./disk_info.txt
        error_free
        echo "disk usage list"
        ls -al *.txt
}

function validate_and_compress(){
        listing_data
        if [[ -f process_info.txt && -f memroy_info.txt && -f disk_info.txt && -f /var/logs/dmesg ]];
        then
                echo "Files are existed and will run the compressing..."
                tar -cfvz files_compressed.tar.gz rocess_info.txt memroy_info.txt disk_info.txt /var/logs/dmesg
                echo "Files are successfully compressed."
                ls -al files_compressed.tar.gz
        else
                echo "There is a missing file."
        fi
}

function ssh_sending(){
        validate_and_compress
        read -p "Enter username: " v_username
        read -p "Enter IP: " v_ip
        read -p "Enter path: " v_path
        rsync -avz files_compressed.tar.gz $v_username@$v_ip:$v_path
}

ssh_sending
